contents :
  - app/views/re_plans               
  - app/views/re_plan_workflows      
  - app/views/re_plan_workflow_rules 
  - app/views/re_workflows
  - app/views/re_workflow_rules
  - app/views/re_publications
  - app/views/re_history

  - public/stylesheets/fancybox
  - public/stylesheets/blueprint
  
  - public/stylesheets/rules_engine
  
  - public/javascripts/rules_engine

  - features/re_pipeline
  
files :  
  - doc/README.rules_engine
  - doc/README.rules_engine_view
  - doc/README.rules_engine_features

  - app/controllers/re_plans_controller.rb               
  - app/controllers/re_plan_workflows_controller.rb      
  - app/controllers/re_plan_workflow_rules_controller.rb 
  - app/controllers/re_workflows_controller.rb
  - app/controllers/re_workflow_rules_controller.rb
  - app/controllers/re_publications_controller.rb
  - app/controllers/re_history_controller.rb

  - app/helpers/rules_engine_helper.rb

  - app/models/re_plan.rb                  
  - app/models/re_plan_workflow.rb         
  - app/models/re_rule.rb                  
  - app/models/re_workflow.rb        

  - app/views/layouts/rules_engine.html.erb

  - config/initializers/rules_engine.rb
  
  - lib/tasks/rules_engine.rake
      
  - db/migrate/20100308225008_create_rules_engine.rb
  
  - public/javascripts/jquery-1.4.2.min.js
  - public/javascripts/jquery.autocomplete.pack.js
  - public/javascripts/jquery.blockUI.js
  - public/javascripts/jquery.fancybox-1.3.1.js
  
  - public/stylesheets/jquery.autocomplete.css
  
  - spec/support/rules_engine_macros.rb
  - spec/support/rules_engine_blueprints.rb  
  
  - spec/helpers/rules_engine_helper_spec.rb
  
  - spec/models/re_plan_spec.rb         
  - spec/models/re_plan_workflow_spec.rb         
  - spec/models/re_rule_spec.rb                  
  - spec/models/re_workflow_spec.rb

  - spec/controllers/re_plans_controller_spec.rb
  
  - features/step_definitions/common/re_debug_steps.rb
  - features/step_definitions/common/re_error_steps.rb      
  - features/step_definitions/common/re_form_steps.rb       
  - features/step_definitions/common/re_model_steps.rb
  - features/step_definitions/common/re_user_steps.rb
  - features/step_definitions/common/re_view_steps.rb

  - features/support/rules_engine.rb