directories :
  list :
    - app/views/re_jobs
    - app/views/re_pipeline_jobs
    - app/views/re_pipeline_rules
    - app/views/re_pipelines

    - public/stylesheets/fancybox
    - public/stylesheets/blueprint
    - public/stylesheets/re_view_box
    - public/stylesheets/re_view_button
    - public/stylesheets/re_view_error
    - public/stylesheets/re_view_navigate
    
    - public/stylesheets/rules_engine
  
    - features/re_pipeline
  
files :  
  - doc/README.rules_engine
  - doc/README.rules_engine_view
  - doc/README.rules_engine_features

  - app/controllers/re_pipelines_controller.rb 
  - app/controllers/re_pipeline_jobs_controller.rb
  - app/controllers/re_pipeline_rules_controller.rb
  - app/controllers/re_jobs_controller.rb

  - app/helpers/re_pipeline_helper.rb

  - app/models/re_pipeline.rb           
  - app/models/re_pipeline_activated.rb 
  - app/models/re_pipeline_activated_observer.rb 
  - app/models/re_pipeline_base.rb      
  - app/models/re_rule.rb               
  - app/models/re_rule_expected_outcome.rb
  - app/models/re_job.rb               
  - app/models/re_job_audit.rb               

  - app/views/layouts/rules_engine.html.erb
  
  - lib/tasks/rules_engine.rake
      
  - db/migrate/20100308225008_create_re_pipelines.rb
  
  - public/javascripts/jquery-1.4.2.min.js
  - public/javascripts/jquery.autocomplete.pack.js
  - public/javascripts/jquery.blockUI.js
  - public/javascripts/jquery.fancybox-1.3.1.js
  
  - public/javascripts/re_job_index.js
  - public/javascripts/re_pipeline_change.js   
  - public/javascripts/re_pipeline_index.js  
  - public/javascripts/re_pipeline_index_jobs.js
  - public/javascripts/re_pipeline_new.js
  - public/javascripts/re_pipeline_show_jobs.js  
  - public/javascripts/re_view.js
  
  - public/stylesheets/jquery.autocomplete.css
  
  - public/stylesheets/rules_engine.css
  - public/stylesheets/re_view_box.css
  - public/stylesheets/re_view_button.css
  - public/stylesheets/re_view_error.css
  - public/stylesheets/re_view_form.css
  - public/stylesheets/re_view_navigate.css
  - public/stylesheets/re_view_table.css          
  - public/stylesheets/re_view.css          
    
  - spec/controllers/re_jobs_controller_spec.rb
  - spec/controllers/re_pipeline_jobs_controller_spec.rb
  - spec/controllers/re_pipeline_rules_controller_spec.rb
  - spec/controllers/re_pipelines_controller_spec.rb
    
  - spec/models/re_pipeline_base_spec.rb
  - spec/models/re_pipeline_spec.rb
  - spec/models/re_pipeline_activated_spec.rb
  - spec/models/re_pipeline_activated_observer_spec.rb
  - spec/models/re_rule_spec.rb
  - spec/models/re_rule_expected_outcome_spec.rb
  - spec/models/re_job_spec.rb
  - spec/models/re_job_audit_spec.rb

  - spec/helpers/re_pipeline_helper_spec.rb
  - spec/support/rules_engine_macros.rb
  
  - features/step_definitions/common/re_debug_steps.rb
  - features/step_definitions/common/re_error_steps.rb      
  - features/step_definitions/common/re_form_steps.rb       
  - features/step_definitions/common/re_model_steps.rb
  - features/step_definitions/common/re_user_steps.rb
  - features/step_definitions/common/re_view_steps.rb

  - features/support/rules_engine.rb
  - features/support/blueprint_re_pipelines.rb

  
  