directories :
  - app/rules
  - spec/lib/rules
  - lib/tasks

templates :
  replacements :
    - complex : rule_name
    - Complex : rule_class
    
  directories : 
    - app/views/re_rule_definitions/complex_rule

  files : 
    - app/rules/complex_rule.rb
    - app/views/re_rule_definitions/complex_rule/_edit.html.erb
    - app/views/re_rule_definitions/complex_rule/_help.html.erb
    - app/views/re_rule_definitions/complex_rule/_workflow.html.erb
    - app/views/re_rule_definitions/complex_rule/_script.html.erb
    - app/views/re_rule_definitions/complex_rule/_title.html.erb
    - app/views/re_rule_definitions/complex_rule/_new.html.erb
    - app/views/re_rule_definitions/complex_rule/_word.html.erb
    - app/views/re_rule_definitions/complex_rule/_words.html.erb
    - spec/lib/rules/complex_rule_spec.rb
