directories :
  - app/rules
  - spec/lib/rules

templates :
  replacements :
    - simple : rule_name
    - RuleSimple : rule_class
    
  directories : 
    - app/views/re_rules/simple

  files : 
    - app/rules/simple.rb
    - app/views/re_rules/simple/_edit.html.erb
    - app/views/re_rules/simple/_form.html.erb
    - app/views/re_rules/simple/_help.html.erb
    - app/views/re_rules/simple/_new.html.erb
    - spec/lib/rules/simple_spec.rb
  
